version: "3"
services:
  app:
    build: .
    container_name: pioner-proxy
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - .env
